### PR TITLE
Using nuget package for Agility SDK instead of storing copy in repository

### PR DESCRIPTION
**Pull request by Devaniti**

### CODE REVIEW

**Comment by sawickiap** [comment]
I added CMakeLists.txt. How would it interact with your solution?

**Comment by Devaniti** [comment]
If it's fine to lock into Visual Studio generator, I can re-implement using that nuget package in Cmake
Cmake 3.15 has nice syntax to reference nuget packages, but that only works with Visual Studio generator

**Comment by Devaniti** [comment]
Either way, approach from this PR is no longer relevant due to switch to cmake, so I'm closing this PR for now

**Comment by sawickiap** [comment]
What is the way to use the Nuget package in Cmake? It's fine to lock into Visual Studio generator.

**Comment by Devaniti** [comment]
Looking second time at this issue, it seems that there's no good way for referencing nuget packages for C++ projects specifically afterall
There's an option in Cmake to reference nuget packages, but seems it only works for C# projects

**Pull request closed without merging**
